### ISSUE TITLE
TLS 사용 여부 설정 옵션 추가하면 어떨까?

### ISSUE THREAD

**Issue by IDKNWHORU** [Ludium-Official/ludium-world-payment#3]
nginx reverse proxy 설정 작업 중에 TLS 사용에 대해 좀 더 유연하게 대처할 수 있는 방법이 떠올랐어. 한번 의견 들어보고 싶어.

## 지금 상황
- payment랑 api 서버에서 TLS/SSL 설정을 직접 하고 있음.
- 이걸 nginx로 https 접속 처리하는 걸로 바꾸려고 하고 있음.

## 이렇게 해보면 어떨까?
1. TLS 쓸지 말지를 환경 변수로 설정할 수 있게 만들어보는 것.
2. 그러면 당장은 nginx에서 https 처리하고 서버에선 TLS 끌 수 있음.
3. 나중에 혹시라도 서버에서 직접 TLS 써야 할 일 생기면 설정만 바꾸면 되니까 편할 것 같아.

## 이렇게 하면 좋을 것 같은 점
- 인프라 구성을 좀 더 자유롭게 할 수 있음.
- 나중에 뭐 바꿔달라고 하면 빨리 대응할 수 있음.
- TLS 관리하기가 더 쉬워질 것 같음.

## 어떻게 만들면 될까요?
환경 변수로 TLS 쓸지 말지 정하려면 아마 이 파일들을 변경해야 되는지 확인 부탁해🙏:

- [src/config/mod.rs](https://github.com/Ludium-Official/ludium-world-payment/blob/5095791a3eed88e190b5172ae4a83c26df367f28/src/config/mod.rs)
- [src/main.rs](https://github.com/Ludium-Official/ludium-world-payment/blob/main/src/main.rs)
- [/docker-compose/production.yml](https://github.com/Ludium-Official/ludium-world-payment/blob/main/docker-compose/production.yml)
- [/docker-compose/development.yml](https://github.com/Ludium-Official/ludium-world-payment/blob/main/docker-compose/development.yml)
- [/.env.example](https://github.com/Ludium-Official/ludium-world-payment/blob/main/.env.example)

이 아이디어에 대해 의견 있으시면 이야기 해줘. 더 좋은 방법이 있다면 그것도 좋아!

Rust 프로젝트는 경험이 없어서 위에 올려놓은 파일들만 고려해야 된다면, 코드 수정해서 PR 올려 놓을게!

**Comment by woon999** [comment]
응 나도 전체적으로 공감해 좋은 것 같아!   

수정해야 하는 코드 파일도 맞아! 변경해야 할 파일은 다음 3개면 돼(이미 아는 내용일 수도 있지만 TMI로 설명도 적어놨어):
- [src/config/mod.rs](https://github.com/Ludium-Official/ludium-world-payment/blob/5095791a3eed88e190b5172ae4a83c26df367f28/src/config/mod.rs): `Config` 구조체에 tls 적용 여부를 판단하는 불 값을 새롭게 추가하면 main에서 접근해서 사용할 수 있어 
- [src/main.rs](https://github.com/Ludium-Official/ludium-world-payment/blob/main/src/main.rs): [L71-L92](https://github.com/Ludium-Official/ludium-world-payment/blob/main/src/main.rs#L71-L92) 현재는 local 실행할 때만 tls을 적용하지 않는데, 이 로직에 분기 조건을 새로운 조건에 맞춰서 수정해주면 될 것 같아
- [/.env.example](https://github.com/Ludium-Official/ludium-world-payment/blob/main/.env.example) : 문서용으로 추가하고 실제 서버 실행할 때는 각 환경에 따라 `.env.{development | production}`에 변수를 tls 적용 여부 변수 넣어주면 돼  (실행 모드 설정은 `.env`에서 `RUN_MODE` 변수로 하고 있어) 
- (+) docker-compose는 포트 변경하고자 한다면 수정해주면 돼
